version: '3.8'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - PORT=3000
    depends_on:
      - db
    volumes:
      - ./:/usr/src/app:cached
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: notebooks
      POSTGRES_USER: notebooks
      POSTGRES_PASSWORD: notebooks
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
    driver: local
