import request from 'supertest';
import { describe, it, expect } from 'vitest';
import createApp from '../src/server/server';

describe('frontend stream shell', () => {
  it('serves the canonical stream shell and stream routes', async () => {
    const app = createApp();

    const home = await request(app).get('/');
    expect(home.status).toBe(200);
    expect(home.text).toContain('id="splash"');
    expect(home.text).toContain('<script src="/public/js/markdown-vendors.js" defer></script>');
    expect(home.text).toContain('<script src="/public/js/shell-nav.js" defer></script>');
    expect(home.text).not.toContain('data-nav="dashboard"');
    expect(home.text).not.toContain('id="loginBtnToolbar"');
    expect(home.text).not.toContain('id="mobOverflowBtn"');
    expect(home.text).toContain('id="treeCurrentLocation"');
    expect(home.text).toContain('tree-current-location--marker');
    for (const nav of ['home', 'science', 'commerce', 'humanities', 'community', 'issues', 'volunteers', 'accounts', 'settings', 'about']) expect(home.text).toContain(`data-nav="${nav}"`);
    expect(home.text).not.toContain('mathjax@3/es5/tex-svg.js');
    expect(home.text).not.toContain('mermaid@11/dist/mermaid.min.js');

    const shell = await request(app).get('/public/html/streams.html');
    expect(shell.status).toBe(200);
    expect(shell.text).toContain('class="stream-shell-page"');
    expect(shell.text).toContain('/public/js/app.js');
    expect(shell.text).not.toContain('openNewMarkdownEditor()');
    expect(shell.text).not.toContain('id="loginBtnToolbar"');
    expect(shell.text).not.toContain('class="mob-toolbar-overflow"');
    expect(shell.text).toContain('tree-current-location--marker');
    expect(shell.text).toContain('/public/js/markdown-editor.js');
    expect(shell.text).toContain('/public/js/markdown-vendors.js');
    expect(shell.text).toContain('id="previewContainer"');
    expect(shell.text).toContain('id="mobilePreview"');
    expect(shell.text).toContain('/public/css/tree.css');
    expect(shell.text).toContain('/public/js/config.js');
    expect(shell.text).toContain('/public/js/shell-nav.js');
    expect(shell.text).not.toContain('/public/client/streams.js');
    expect(shell.text).toContain('/public/client/observability.js');

    const dashboard = await request(app).get('/dashboard');
    expect(dashboard.status).toBe(302);
    expect(dashboard.headers.location).toBe('/settings#personal-space');

    const settings = await request(app).get('/settings');
    expect(settings.status).toBe(200);
    expect(settings.text).toContain('Your Dashboard');
    expect(settings.text).toContain('class="settings-sidebar"');
    expect(settings.text).toContain('href="#personal-space"');
    expect(settings.text).toContain('href="#appearance"');
    expect(settings.text).toContain('href="#reading-controls"');
    expect(settings.text).not.toContain('href="#account-settings"');
    expect(settings.text).not.toContain('Sign in later');
    expect(settings.text).not.toContain('Sign in / create account');
    expect(settings.text).not.toContain('data-nav="dashboard"');
    expect(settings.text).toContain('id="personal-space"');
    expect(settings.text).toContain('id="themePreset"');
    expect(settings.text).toContain('id="themePersistenceStatus"');
    expect(settings.text).toContain('id="appearance"');
    expect(settings.text).toContain('id="themePresetGallery"');
    expect(settings.text).toContain('id="themeModeToggle"');
    expect(settings.text).toContain('Every theme family includes a coordinated light and dark variant.');
    expect(settings.text).toContain('<option value="classic">Classic</option>');
    expect(settings.text).not.toContain('<option value="classic">Classic light</option>');
    expect(settings.text).toContain('/public/client/observability.js');
    expect(settings.text).toContain('/public/js/shell-nav.js');
    expect(settings.text).toContain('/public/js/session-state.js');
    expect(settings.text).toContain('/public/js/sw-register.js');
    expect(settings.text).toContain('/public/js/settings-nav.js');
    expect(settings.text).not.toContain('/public/js/app.js');
    expect(settings.text).not.toContain('/public/js/stream-runtime.js');
    expect(settings.text).toContain('id="reading-controls"');
    expect(settings.text).toContain('id="readingFontSize"');
    expect(settings.text).toContain('id="readingWidth"');
    expect(settings.text).toContain('id="readingLineHeight"');
    expect(settings.text).toContain('id="readingCodeWrap"');
    expect(settings.text).toContain('id="readingReducedMotion"');
    expect(settings.text).toContain('class="settings-subsection"');
    const shellNavJs = await request(app).get('/public/js/shell-nav.js');
    expect(shellNavJs.status).toBe(200);
    expect(shellNavJs.text).toContain('__noteBooksShellNavInitialized');
    const settingsNavJs = await request(app).get('/public/js/settings-nav.js');
    expect(settingsNavJs.status).toBe(200);
    expect(settingsNavJs.text).toContain('__noteBooksSettingsNavInitialized');
    const themeJs = await request(app).get('/public/js/theme.js');
    expect(themeJs.status).toBe(200);
    expect(themeJs.text).toContain('/api/themes');
    expect(themeJs.text).toContain('/api/session');
    expect(themeJs.text).toContain('persistCustomTheme');
    expect(themeJs.text).toContain('renderThemePresetGallery');
    expect(themeJs.text).toContain('aria-pressed');
    expect(themeJs.text).toContain('toggleThemeMode');
    expect(themeJs.text).toContain('themeMode');
    expect(themeJs.text).toContain("surfaceStrong");
    expect(themeJs.text).toContain("session.themeMode === 'dark'");
    expect(themeJs.text).not.toContain("data-theme = values.texture");
    expect(themeJs.text).toContain("inputBg");
    expect(themeJs.text).toContain("codeText");
    expect(themeJs.text).toContain("surface: '#262b32'");
    expect(themeJs.text).toContain("bg: '#1b1f24'");
    const session = await request(app).get('/api/session');
    expect(session.status).toBe(200);
    expect(session.headers['set-cookie']?.some((cookie: string) => cookie.startsWith('nb_sid='))).toBe(true);
    const themes = await request(app).get('/api/themes');
    expect(themes.status).toBe(200);
    expect(themes.body.themes.length).toBeGreaterThanOrEqual(5);

    const requestJs = await request(app).get('/public/js/request.js');
    expect(requestJs.status).toBe(200);
    expect(requestJs.text).toContain("fetch('/api/session'");
    expect(requestJs.text).toContain('x-csrf-token');
    expect(requestJs.text).toContain('response.status === 403');
    const sessionStateJs = await request(app).get('/public/js/session-state.js');
    expect(sessionStateJs.status).toBe(200);
    expect(sessionStateJs.text).toContain('noteBooksSession');
    expect(sessionStateJs.text).toContain('AbortController');
    const dashboardJs = await request(app).get('/public/js/dashboard.js');
    expect(dashboardJs.status).toBe(200);
    expect(dashboardJs.text).toContain('noteBooksRequestJson');
    const readingJs = await request(app).get('/public/js/reading-preferences.js');
    expect(readingJs.status).toBe(200);
    expect(readingJs.text).toContain('persistReadingPreferences');
    expect(readingJs.text).toContain('--reader-content-width');
    const swRegisterJs = await request(app).get('/public/js/sw-register.js');
    expect(swRegisterJs.status).toBe(200);
    expect(swRegisterJs.text).toContain('20260828-sw-v43');
    const appJs = await request(app).get('/public/js/app.js');
    expect(appJs.status).toBe(200);
    expect(appJs.text).toContain('20260828-sw-v43');
    expect(appJs.text).toContain('Edit existing Markdown file');
    expect(appJs.text).toContain('isNewFile: false');
    expect(appJs.text).toContain('window.NoteBooksRawDelivery');
    expect(appJs.text).toContain('const delivery = window.NoteBooksRawDelivery;');
    expect(appJs.text).toContain('getVisibleTreeRows');
    expect(appJs.text).toContain('aria-activedescendant');
    expect(appJs.text).toContain("event.key === 'ArrowRight'");
    expect(appJs.text).not.toContain('const sourceCandidates = (p, forEmbed) => {');
    expect(appJs.text).not.toContain("method: 'HEAD'");
    expect(appJs.text).toContain('const rawUrl = await resolveSourceUrl(path);');
    expect(appJs.text).toContain('const targetPath = repo ? (repoPath || path) : path;');
    expect(appJs.text).not.toContain('navigateToRoute(');
    expect(appJs.text).not.toContain('window.addEventListener(\'popstate\'');
    expect(appJs.text).toContain("if (!slug) return '';");
    expect(appJs.text).toContain('let defaultLandingMarkup = null;');
    expect(appJs.text).toContain('landing.innerHTML = defaultLandingMarkup;');
    expect(appJs.text).toContain('landing.hidden = !isPortalRoute;');
    expect(appJs.text).toContain("document.title = 'NoteBooks';");
    expect(appJs.text).toContain('let updatePollingStarted = false;');
    expect(appJs.text).toContain('function hideSplash()');
    expect(appJs.text).toContain('if (isPortalRoute) hideSplash();');
    expect(appJs.text).toContain('const proxied = await resolveSourceUrl(targetPath);');
    expect(appJs.text).not.toContain('resolvePdfPreviewUrl');
    expect(appJs.text).not.toContain('/api/registry?${Date.now()}');
    expect(appJs.text).not.toContain('/files.json?${Date.now()}');

    const vendorLoader = await request(app).get('/public/js/markdown-vendors.js');
    expect(vendorLoader.status).toBe(200);
    expect(vendorLoader.text).toContain('NoteBooksMarkdownVendors');
    expect(vendorLoader.text).toContain('Promise.allSettled');

    const rawDelivery = await request(app).get('/public/js/raw-delivery.js');
    expect(rawDelivery.status).toBe(200);
    expect(rawDelivery.text).toContain('window.NoteBooksRawDelivery');

    const authJs = await request(app).get('/public/js/auth.js');
    expect(authJs.status).toBe(200);
    expect(authJs.text).toContain('updateShellSidebar();');
    expect(authJs.text).not.toContain('if (!loginBtn)\n        return;');
    const mobileJs = await request(app).get('/public/js/mobile.js');
    expect(mobileJs.status).toBe(200);
    expect(mobileJs.text).toContain('Edit existing Markdown file');
    expect(mobileJs.text).toContain("selected.repo || ''");
    expect(mobileJs.text).not.toContain('restoreModernSession();');
    expect(mobileJs.text).toContain('updatePendingBadge();');

    const streamShell = await request(app).get('/public/html/streams.html');
    expect(streamShell.status).toBe(200);
    expect(streamShell.text).toContain('/public/js/session-state.js');
    expect(streamShell.text).toContain('/public/css/tree.css?v=20260830-tree-v2');
    expect(streamShell.text.indexOf('/public/js/session-state.js')).toBeLessThan(streamShell.text.indexOf('/public/js/theme.js'));
    const portalShell = await request(app).get('/public/html/portal.html');
    expect(portalShell.status).toBe(200);
    expect(portalShell.text).toContain('/public/js/session-state.js');
    expect(portalShell.text).not.toContain('/public/js/config.js');

    const streamsJs = await request(app).get('/public/client/streams.js');
    expect(streamsJs.status).toBe(200);
    expect(streamsJs.text).toContain('initStreamShell');
    expect(streamsJs.text).toContain('STREAM_SHELL_ARTIFACTS');
    expect(streamsJs.text).not.toContain('const STREAM_ARTIFACTS');
    expect(streamsJs.text).not.toContain('?_=${Date.now()}');

    const serviceWorker = await request(app).get('/service-worker.js');
    expect(serviceWorker.status).toBe(200);
    expect(serviceWorker.text).toContain("const CACHE_VERSION = 'webman-v47'");
    expect(serviceWorker.text).toContain('public/client/observability.js');
    expect(serviceWorker.text).toContain('function cacheStaticResponse');
    expect(serviceWorker.text).toContain('Cache failures must never reject the page');
    expect(serviceWorker.text).toContain('public/css/tree.css');
    expect(serviceWorker.text).toContain('Admin routes must always follow the server/Vercel route decision.');
    expect(serviceWorker.text).toContain('Do not fan out to all remote stream APIs during installation.');
    for (const asset of ['public/favicon-128.png', 'public/json/github-repos.json', 'public/js/markdown-vendors.js', 'public/js/theme.js', 'public/js/reading-preferences.js', 'public/js/landing-docs.js', 'public/js/stream-runtime.js', 'public/js/raw-delivery.js', 'public/js/portal.js', 'public/js/shell-nav.js', 'public/js/session-state.js', 'public/js/sw-register.js', 'public/html/settings.html', 'public/html/portal.html', 'public/json/science-tree.json', 'public/json/commerce-tree.json', 'public/json/humanities-tree.json']) {
      expect(serviceWorker.text).toContain(asset);
    }

    const streamsCss = await request(app).get('/public/css/streams.css');
    expect(streamsCss.status).toBe(200);
    const styleCss = await request(app).get('/public/css/style.css');
    expect(styleCss.status).toBe(200);
    expect(styleCss.text).toContain('.stream-card');
    expect(styleCss.text).toContain('Global theme bridge');
    expect(styleCss.text).toContain('.markdown-renderer pre');
    expect(styleCss.text).toContain('--surface-strong');
    expect(styleCss.text).toContain('html[data-theme-texture="grid"] .stream-shell-page');
    expect(styleCss.text).toContain('.stream-shell-page .global-nav { background: color-mix');
    expect(styleCss.text).toContain('grid-template-areas: "tree workspace"');
    expect(styleCss.text).toContain('.tree-current-location--marker');
    expect(styleCss.text).toContain('.toolbar > button');
    const treeCss = await request(app).get('/public/css/tree.css');
    expect(treeCss.status).toBe(200);
    expect(treeCss.text).toContain('flex-direction: column');
    expect(treeCss.text).toContain('border: 0 !important');
    expect(treeCss.text).toContain('sidebar-tree-row::before');
    expect(treeCss.text).toContain('display: none !important');

    const page = await request(app).get('/science');
    expect(page.status).toBe(200);
    expect(page.text).toContain('class="stream-shell-page"');

    const portal = await request(app).get('/community');
    expect(portal.status).toBe(200);
    expect(portal.text).toContain('class="portal-shell-page"');
    expect(portal.text).toContain('/public/js/portal.js');
    expect(portal.text).toContain('/public/client/observability.js');
    expect(portal.text).not.toContain('/public/js/app.js');
    expect(portal.text).not.toContain('data-nav="dashboard"');
    expect(portal.text).toContain('data-nav="volunteers"');
    expect(portal.text).toContain('data-nav="about"');

    const about = await request(app).get('/about');
    expect(about.status).toBe(200);
    expect(about.text).toContain('data-nav="about"');
    expect(about.text).toContain('/public/js/portal.js');
    const aboutRuntime = await request(app).get('/public/js/portal.js');
    expect(aboutRuntime.status).toBe(200);
    expect(aboutRuntime.text).toContain('about-idea-title');
    expect(aboutRuntime.text).toContain('about-inspirations-title');
    expect(aboutRuntime.text).toContain('about-contributors-title');
    expect(aboutRuntime.text).toContain('about-page');
    expect(aboutRuntime.text).toContain("if (slug === 'about')");
    expect(aboutRuntime.text).toContain('return;');

    const adminShell = await request(app).get('/admin');
    expect(adminShell.status).toBe(200);
    expect(adminShell.text).not.toContain('data-nav="dashboard"');

    const admin = await request(app).get('/admin-prs');
    expect(admin.status).toBe(200);
    expect(admin.text).toContain('for="assign-role-email"');
    expect(admin.text).toContain('for="assign-role-role"');
    expect(admin.text).toContain('for="totp-verify-token"');

    const issues = await request(app).get('/issues');
    expect(issues.status).toBe(200);
    expect(issues.text).toContain('class="portal-shell-page"');
  });
});
